# -*- coding: utf-8 -*-
"""ExploringDaft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qfkQku0Bo8LiSRcG9BiTmheDHU-O7VH
"""

!pip install -q pandas pyarrow daft duckdb

import time
import pandas as pd
import daft
import pyarrow as pa
from daft import col

url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet"
print("Loading dataset...")
df_pd = pd.read_parquet(url)
print(f"Dataset shape: {df_pd.shape}")
df_pd.head()

df_arrow = pa.Table.from_pandas(df_pd)
df_daft = daft.from_arrow(df_arrow)

print("\nQuery: Average fare amount per passenger count (fares > $10)\n")

start = time.time()
result_pd = (
    df_pd[df_pd["fare_amount"] > 10]
    .groupby("passenger_count")["fare_amount"]
    .mean()
    .reset_index()
)
t_pandas = time.time() - start
print(f"Pandas time: {t_pandas:.2f}s")

start = time.time()
result_daft = (
    df_daft.where(col("fare_amount") > 10)
    .groupby("passenger_count")
    .agg(col("fare_amount").mean().alias("avg_fare"))
)
result_daft = result_daft.to_pandas()
t_daft = time.time() - start
print(f"Daft time: {t_daft:.2f}s")

print("\nResults:")
display(result_pd.head(10))
display(result_daft.head(10))

print(f"\n Performance Comparison: Daft = {t_daft:.2f}s | Pandas = {t_pandas:.2f}s")
